### ISSUE TITLE
Ciatah skipping files

### ISSUE THREAD

**Issue by NataliaFavila** [bahanonu/ciatah#110]
Dear Biafra,

we are running Ciatah (latest version) on matlab 2020 and 2021, and turboreging the videos (.h5).
However, we manage to run it once correctly and then we ge the following error:

-------------------
1/1: D:\favilan
SKIPPING ANALYSIS FOR THIS FOLDER
pre-allocating movies to display...
Miji loaded!
-------------------

It seems to be skipping folders for some reason?
Could you help us?

Thanks!
Natalia

**Comment by bahanonu** [comment]
@NataliaFavila There should be a file in those folders called `_currentlyAnalyzingFolderCheck.mat` that if CIAtah sees it will skip that folder. This is useful when you are running analysis from the same shared storage and group of folders (e.g. a local server) across multiple workstations and want workstations to skip that folder if another workstation is analyzing it. 

Most users do not need this, so it is turned off by default. In your settings while running `modelPreprocessMovie` did you change from the default

![image](https://user-images.githubusercontent.com/5241605/199320327-2be5ce20-244d-4c6a-a4b1-fc2a4c68d991.png)

to the below? That might explain why it is skipping that folder. If you change it back this issue should go away.

![image](https://user-images.githubusercontent.com/5241605/199320375-c99ed347-889b-4e41-b5b0-034da6e204eb.png)
