### ISSUE TITLE
How to use viewCellExtractionOnMovie?

### ISSUE THREAD

**Issue by RandallJEllis** [bahanonu/ciatah#126]
I have a bigTIFF video and have ran downsampling, motion correction, df/f, followed by CNMF-E (saved in .NWB format). I'm not sure how to correctly run viewCellExtractionOnMovie to obtain something like what's in the step-by-step [guide](https://bahanonu.github.io/ciatah/pipeline_detailed_all/) where the outlines of extracted cells are superimposed on the video. When I run it via the GUI, I can get the video to display but there aren't any outlines. The .NWB output of CNMF-E is in the same folder as the video. Any help is appreciated!

**Comment by bahanonu** [comment]
@RandallJEllis Is the cell-extraction file format in the main GUI is set to NWB format (see below)?

![image](https://user-images.githubusercontent.com/5241605/226418702-770beb42-037e-4623-b55b-1bb3926cbea7.png)

And by default ciatah looks for NWB cell extraction files in the `nwbFiles` sub-folder within each analysis folder (see https://bahanonu.github.io/ciatah/data/#nwb-support). Can have ciatah search just the analysis folder by running `obj.setMovieInfo;` and setting the last option to blank, see below. I'd considered making ciatah fallback to searching the root directory for NWB cell extraction if `nwbFiles` sub-folder does not exist, might look into that again and implement.

I'll update the guide to make these details clearer.

![image](https://user-images.githubusercontent.com/5241605/226417089-b56ea7c8-19a9-4b07-996d-981ee32ac19a.png)

![image](https://user-images.githubusercontent.com/5241605/226417271-9fc06c6f-0eba-4169-8e1e-2b67f084dec0.png)

**Comment by RandallJEllis** [comment]
Hi Biafra, thank you. This is what I'm seeing: 

![1](https://user-images.githubusercontent.com/7551835/226713827-3fcd4909-d303-41da-b52e-210bffdab025.PNG)

![2](https://user-images.githubusercontent.com/7551835/226713863-02c281f7-4815-4591-aa64-e2ffe0d36f10.PNG)
 
![3](https://user-images.githubusercontent.com/7551835/226714173-d7906e63-e084-495f-9783-3d22b016fc76.PNG)

In the traceback, I see this:

```
Using secondary TIFF loading...
BigTIFF.
loading ImageJ tif: 0|10|20|30|40|50|60|70|80|90|100
Elapsed time is 8.340679 seconds.
movie class: uint8
movie size: 1536  2048   500
x-dims: 1536
y-dims: 2048
z-dims: 500
movie size: 1499.9995Mb | 1536  2048   500 | uint8
Elapsed time is 8.880069 seconds.
###
Search: _cnmfeAnalysis.mat
no files
Adding outlines to cells: 0|10|20|30|40|50|60|70|80|90|100
```

As you can see, no outlines. I do not have a file named `_cnmfeAnalysis.mat`, but I did not see anywhere to specify this. My CNMFE filename is `_cnmfe_16cellwidth_800tau_2.5minpnrres_2minpnr.nwb`

**Comment by sammyhansali** [comment]
Hi Biafra,

Randy and I are working on the same dataset and similar configuration.

I modified Randy's folder structure to put the .nwb file from CNMFE extraction in a subfolder named 'nwbFiles'.

CIAtah was able to read my nwb file but as you can see from the below screenshot - the signalPeaks, signalPeaksArray, and valid all have "0  0" values whereas yours didn't in the tutorial video.

Is the _cnmfeAnalysis.mat file necessary for viewCellExtractionOnMovie to function? If so how to generate it?

![image](https://user-images.githubusercontent.com/40586027/227014176-680df0c5-a20b-49e9-aaa7-c72fdf98f1c0.png)

**Comment by bahanonu** [comment]
Great to hear that modification worked and looks like from the matrix/tensor size loaded that the nwb files are being read correctly. Can you send me the NWB file to check? As loading should work in root folder if sub-folder is set to blank else can push out an update.

It looks like the X × Y size of the cell extraction outputs in the NWB file (384 × 512) is spatially 4x downsampled compared to the movie (1536 × 2048).
- Is the displayed movie the same movie that was used to run cell extraction?
- If you are loading the movie into RAM (or pre-loading) then you can also enable 4x downsampling in `viewCellExtractionOnMovie` options (see below with `Simple settings` chosen). 

![image](https://user-images.githubusercontent.com/5241605/227031514-030ab3fe-5251-430b-8f9c-f77718184989.png)

Also, could you send a screenshot of the options dialog in `viewCellExtractionOnMovie`? It is likely that you will have to run `obj.modelVarsFromFiles`, see https://bahanonu.github.io/ciatah/pipeline_detailed_signal_extraction_load/#loading-cell-extraction-output-data-with-modelvarsfromfiles.
- That will only need to be run once after loading that instance of ciatah with that folder.
- If you select to pre-load the movie, it will automatically also check whether signal peaks have been calculated and run that method if not (I'll see about changing this behavior to include non-preloaded cases with `viewCellExtractionOnMovie`, I've added auto-loading to a number of ciatah methods to hopefully reduce user confusion). But the signal peaks are not necessary for this function.

**Comment by RandallJEllis** [comment]
Thanks Biafra, I got it to work using your changes, and I was able to keep the NWB file in the root folder. Here are my screenshots:

![1_03232023](https://user-images.githubusercontent.com/7551835/227294055-a236c1bf-1963-499e-9b1f-5b72edf5c2cb.PNG)
![2_03232023](https://user-images.githubusercontent.com/7551835/227294149-195af076-673c-4b06-8612-667d238352fc.PNG)

**Comment by RandallJEllis** [comment]
Sorry Biafra, now I have another issue. While I'm able to visualize the cell extractions on the raw movie, I'm having trouble visualizing them on the dfof movie (which CNMF-E was ran on and has been downsampled 4x). I thought it would be a simple change but I'm getting a `Unrecognized field name "GroupHierarchy".` error. Here are my screenshots (`dfof` is the regex for the dfof movie):

![1111](https://user-images.githubusercontent.com/7551835/227308705-5a4360ab-4dfa-4ea0-bfb7-e4b3f0433e23.PNG)
![222222](https://user-images.githubusercontent.com/7551835/227308736-e6f8dc81-1368-4a62-a1ec-9171212831da.PNG)
![33333](https://user-images.githubusercontent.com/7551835/227308766-29ce1cb5-4f09-4a43-acbe-4305ea07a633.PNG)

**Comment by sammyhansali** [comment]
Yes, thanks Biafra!
