### ISSUE TITLE
GUI very ugly

### ISSUE THREAD

**Issue by Silver-Fang** [bahanonu/ciatah#88]
![屏幕截图 2021-10-21 112742](https://user-images.githubusercontent.com/33191697/138206865-db433a57-dfb7-4836-a3db-2693fdf36b79.png)
A bunch of warnings pops up as soon as I open it. The command line font is adjusted very small, and there are a lot of garbled characters. The font of the graphical interface is instead too large, causing the display to be truncated.
This extremely terrible GUI makes my first impression very bad, and now I have no desire to use it at all.
I recommend that if the GUI is not well done, don't show it, and honestly do a pure codeful API.

**Comment by bahanonu** [comment]
There is a command-line base API (`ciapkg.api`), see example at https://bahanonu.github.io/ciatah/api_example_pipeline/.

CIAtah has not been tested on 2021b nor with non-English Matlab. On English MATLAB that warning shows up as `Warning: The JavaFrame figure property will be removed in a future release. For more information see UI Alternatives for MATLAB Apps on mathworks.com. `. It does not impact CIAtah performance until MathWorks removes JavaFrame.

Can scale GUI font with `fontSizeGuiScale` property in CIAtah object, e.g. `obj.fontSizeGuiScale = 0.7` to scale everything by 70%. On a monitor with higher resolution than SB2 and scaling at 200% (Windows), I get below when GUI maximized without modifying `fontSizeGuiScale`.
![image](https://user-images.githubusercontent.com/5241605/141508624-1379906e-22cf-445d-b997-6a102d810d67.png)
