### ISSUE TITLE
Can`t install 

### ISSUE THREAD

**Issue by nobody15469** [bahanonu/ciatah#93]
Hi Biafra,

I'm trying to run CIAtah 4.0 on MATLAB R2020b, on a windows.
but i even cant install it well.
I cant find the file    cvx_setup.m   (likely` calcuumagingAnalysis/_external_programs/cvx_rd`).

**Comment by bahanonu** [comment]
Hi, to help debug your issue, can you provide the commands you used when trying to setup `ciatah`?

**Comment by nobody15469** [comment]
hi Biafra, 

I am just following your quick start guide in github. Sorry for Chinese word in document.  I am new to programming and github. Thank you for your quick response.

![屏幕截图 2021-12-01 164733](https://user-images.githubusercontent.com/95337864/144201645-91f15b30-f544-4757-a480-202f2a3cd397.png)


[error.docx](https://github.com/bahanonu/ciatah/files/7632250/error.docx)

**Comment by bahanonu** [comment]
Thanks for the additional information. It looks like you are having trouble downloading many of the dependencies, so need to determine if that is a connectivity issue.

Can you run `ciapkg.io.loadDependencies();`? A dialog like the below should appear, press okay for that and the next dialog then send me the output.

![image](https://user-images.githubusercontent.com/5241605/144356548-3fc1952e-3e02-45c9-b556-914d501a9248.png)

Alternatively, let me know if you are able to directly download missing files, see `Direct download` section at:
https://github.com/bahanonu/ciatah/tree/bahanonu/functionUpdates/_external_programs#direct-download
