### ISSUE TITLE
Error: Undefined function 'getFileList'

### ISSUE THREAD

**Issue by LaSal2090** [bahanonu/ciatah#95]
Hi,

after some hours of trying to get Ciatah to run, I installed it anew by cloning it from github with matlab and decided to ask for help. I wanted to test varius functions of Ciatah and use it for cellextraction from 1photon miniscope data. 

I started by using the function modelDownsampleRawMovies. After the input GUI it returns following error message.

![Capture](https://user-images.githubusercontent.com/95704246/145065709-0696f7fd-b257-42c4-9154-ed123fb32475.PNG)

I tried the function viewMovieRegistrationTest and get the same error message. I am running Matlab2020b, all dependencies are loaded correctly, as it is stated when starting up Ciatah. 

Where  is my mistake? any help is appreciated

Regards

**Comment by bahanonu** [comment]
Thanks for reaching out on this. I've updated the repo to handle this error, let me know if this issue still occurs on your end after re-cloning.
